apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.authService.image.repository }}:{{ .Values.authService.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=(localdb)\\mssqllocaldb;Database=AuthServiceDb;Trusted_Connection=True;"
            - name: Jwt__Key
              value: "your_very_long_and_secure_secret_key_1234567890"
            - name: Jwt__Issuer
              value: "your_unique_issuer"