authService:
  image:
    repository: your-docker-repo/auth-service
    tag: latest
  service:
    type: ClusterIP
    port: 80

businessService:
  image:
    repository: your-docker-repo/business-service
    tag: latest
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: your-docker-repo/frontend
    tag: latest
  service:
    type: ClusterIP
    port: 3000